<a href="https://colab.research.google.com/github/karthika95/Data_inference/blob/main/presentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
conf_mat=pd.read_csv("/Data_inference/conf_mat.csv")

In [3]:
# conf_mat

,Unnamed: 0,Labels,Test Support,Training_support,rsp,ras-neg,rh,k2,lwg__psp,rt,...,rad,rbmod__relc,nmod,lwg__vaux_cont,_,main,k7,ras-k4,rbmod,pof__inv
0,0,rsp,21,155,15,0,0,0,0,0,...,0,0,4,0,0,0,0,0,0,0
1,1,ras-neg,8,68,0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,rh,143,1280,0,0,124,5,0,2,...,0,0,0,0,0,0,1,0,0,0
3,3,k2,1926,14350,0,0,4,1515,1,3,...,0,0,6,0,0,1,6,0,0,0
4,4,lwg__psp,8143,63001,0,0,0,2,8123,0,...,0,0,0,0,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,70,main,1804,14089,0,0,0,1,0,2,...,0,0,0,0,0,1764,0,0,0,0
71,71,k7,1169,8690,0,0,0,1,1,0,...,0,0,2,0,0,1,948,0,0,0
72,72,ras-k4,0,6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
73,73,rbmod,6,33,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,5,0
74,74,pof__inv,1,Not in training data,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
# conf_mat.to_csv('/Data_inference/conf_mat.csv')

#Label meanings

In [5]:
meanings=pd.read_csv("/Data_inference/label_meanings.csv")

In [6]:
df=pd.read_csv("/Data_inference/final_file.csv")

In [7]:
path="/Data_inference/final_file.tsv"
train = pd.read_csv(path,sep='\t', encoding='utf-8')

In [8]:
# df.head()

In [9]:
# meanings.head()

#Support

In [10]:
def support(label1,label2):
  idx_l1=int(conf_mat[conf_mat['Labels']==label1].index.values)
  idx_l2=int(conf_mat[conf_mat['Labels']==label2].index.values)
  columns=['label','Train_support','Test_support']
  support=pd.DataFrame(columns=columns)
  support.loc[len(support.index)] = [label1, conf_mat['Training_support'][idx_l1], conf_mat['Test Support'][idx_l1]]
  support.loc[len(support.index)] = [label2, conf_mat['Training_support'][idx_l2], conf_mat['Test Support'][idx_l2]]
  print(support)

#Confusion Pair

In [16]:
def info(count,idx,label1,label2):
  columns=['label_type','labels','Meaning_Sanskrit','Meaning_English']
  conf=pd.DataFrame(columns=columns)
  conf['label_type']=['annotated label', 'predicted label']
  conf['labels']=[label1,label2]
  def meaningS(i):
    return meanings.loc[meanings['Label'] == conf['labels'][i], 'Meaning(Sanskrit)'].iloc[0]
  def meaningE(i):
    return meanings.loc[meanings['Label'] == conf['labels'][i], 'Meaning(English)'].iloc[0]
  if label1 in meanings['Label'].values:
    if label2 in meanings['Label'].values:
      conf['Meaning_Sanskrit']= [meaningS(0),meaningS(1)]
      conf['Meaning_English']=[meaningE(0),meaningE(1)]
    else:
      conf['Meaning_English'][0]=meaningE(0)
      conf['Meaning_Sanskrit'][0]=meaningS(0)
  elif label2 in meanings['Label'].values:
    conf['Meaning_English'][1]=meaningE(1)
    conf['Meaning_Sanskrit'][1]=meaningS(1)
  print("Wrongly predicted sentence\n")
  print(df['sentence'][idx] + "\nword: "+ df['FORM'][idx] +"\thead: " + str(df['HEAD'][idx]) + "\tsent_id: " + str(df['ID'][idx]) + "\n")
  if(count==0):
    print(conf)
    print("\n")
    print(support(label1,label2))
    count+=1

    print("Examples of "+label1+"\n")
    c=1;
    for idx in range(len(train)):
      if train['karka Relation'][idx]==label1:
        print(train['sentence'][idx] + "\nword: "+ train['Inflection/Surface form'][idx] +"\thead: " + str(train['head_inflection'][idx]) + "\tsent_id: " + str(df['ID'][idx]) + "\n")
        c+=1
      if c>3:
        break       
    print("Examples of "+str(label2)+"\n")
    c=1;
    for idx in range(len(train)):
      if train['karka Relation'][idx]==label2:
        print(train['sentence'][idx] + "\nword: "+ train['Inflection/Surface form'][idx] +"\thead: " + str(train['head_inflection'][idx]) + "\tsent_id: " + str(df['ID'][idx]) + "\n")
        c+=1
      if c>3:
        break  
  
  input("Press Enter for next example: ")

In [12]:
# train.head()

,sent_id,index,sentence,Inflection/Surface form,Stem / Root,Category,Gender,Number,Person,Case,Vib,TAM,Voice,head_inflection,head_stem,karka Relation
0,1,1,पांच लाख का इनामी और कुख्यात स्वयंभू नक्सल कमा...,पांच,पांच,num,any,any,-,any,-,-,-,लाख,लाख,mod
1,1,2,पांच लाख का इनामी और कुख्यात स्वयंभू नक्सल कमा...,लाख,लाख,num,any,any,-,o,0_का,-,-,इनामी,इनामी,r6
2,1,3,पांच लाख का इनामी और कुख्यात स्वयंभू नक्सल कमा...,का,का,psp,m,sg,-,d,-,-,-,लाख,लाख,lwg__psp
3,1,4,पांच लाख का इनामी और कुख्यात स्वयंभू नक्सल कमा...,इनामी,इनामी,adj,any,any,-,d,-,-,-,और,और,ccof
4,1,5,पांच लाख का इनामी और कुख्यात स्वयंभू नक्सल कमा...,और,और,avy,-,-,-,-,-,-,-,बैठा,बैठा,nmod

In [17]:
count=0
label1=input("Annotated label: ")
label2=input("Predicted label: ")
print("\n")
for idx in range(len(df)):
  if df['DEPREL'][idx]==label1 and df['DEPREL_PRED'][idx]==label2:
    info(count,idx,label1,label2)
    count+=1
if idx>=(len(df)-1):
  print("No more confustion pairs..")

Annotated label: k1
Predicted label: k2


Wrongly predicted sentence

देवी की प्रतिमा जिस स्थान पर रखी गई है उसी पवित्र स्थल के आसपास भक्त बैठे रहते हैं तथा आराधना करते हैं ।
word: प्रतिमा	head: 7	sent_id: 3

        label_type labels Meaning_Sanskrit     Meaning_English
0  annotated label     k1           kartaa  doer/agent/subject
1  predicted label     k2            karma      object/patient


  label Train_support Test_support
0    k1         19332         2302
1    k2         14350         1926
None
Examples of k1

पांच लाख का इनामी और कुख्यात स्वयंभू नक्सल कमांडर कमलेश्वर बैठा पटना के बाहरी इलाके में पकड़ा गया है .

उत्तर प्रदेश , बिहार और झारखंड की पुलिस उसे पिछले एक दशक से तलाश रही थी .

यह खूंखार नक्सली ७० पुलिस कर्मियों की हत्या का जिम्मेदार तो है ही उसने बारूदी सुरंगों के विस्फोटों से अनेक लोगों की जानें ली हैं .

Examples of k2

उत्तर प्रदेश , बिहार और झारखंड की पुलिस उसे पिछले एक दशक से तलाश रही थी .
word: उसे	head: तलाश	sent_id: 15

यह खूंखार नक्सली ७० पुलिस कर्मियों की हत्या का जिम्मेदार तो है ही उसने बारूदी सुरंगों के विस्फोटों से अनेक लोगों की जानें ली हैं .
word: जानें	head: ली	sent_id: 5

डीआईजी पुलिस अशीष रंजन ने संवाददाताओं को सोमवार की रात बताया कि सुराग लगते ही एसटीएफ के कमांडो ने स्थानीय पुलिस और उत्तर प्रदेश से आए एसटीएफ के लोगों के साथ मिलकर एक सघन तलाशी अभियान चलाया .
word: कि	head: बताया	sent_id: 18

Press Enter for next example:
Wrongly predicted sentence

भारत के सांस्कृतिक धार्मिक तीर्थ स्थलों में माँ काली का मंदिर सबसे प्राचीन माना जाता है ।
word: मंदिर	head: 14	sent_id: 11

KeyboardInterrupt: ignored