<a href="https://colab.research.google.com/github/karthika95/Data_inference/blob/main/presentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd

In [28]:
conf_mat=pd.read_csv("/content/drive/MyDrive/nltm/label_inference/conf_mat.csv")

In [29]:
conf_mat

,Unnamed: 0,Labels,Test Support,Training_support,rsp,ras-neg,rh,k2,lwg__psp,rt,...,rad,rbmod__relc,nmod,lwg__vaux_cont,_,main,k7,ras-k4,rbmod,pof__inv
0,0,rsp,21,155,15,0,0,0,0,0,...,0,0,4,0,0,0,0,0,0,0
1,1,ras-neg,8,68,0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,rh,143,1280,0,0,124,5,0,2,...,0,0,0,0,0,0,1,0,0,0
3,3,k2,1926,14350,0,0,4,1515,1,3,...,0,0,6,0,0,1,6,0,0,0
4,4,lwg__psp,8143,63001,0,0,0,2,8123,0,...,0,0,0,0,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,70,main,1804,14089,0,0,0,1,0,2,...,0,0,0,0,0,1764,0,0,0,0
71,71,k7,1169,8690,0,0,0,1,1,0,...,0,0,2,0,0,1,948,0,0,0
72,72,ras-k4,0,6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
73,73,rbmod,6,33,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,5,0
74,74,pof__inv,1,Not in training data,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# conf_mat.to_csv('/content/drive/MyDrive/nltm/label_inference/conf_mat.csv')

#Label meanings

In [30]:
meanings=pd.read_csv("/content/drive/MyDrive/nltm/label_inference/label_meanings.csv")

In [31]:
df=pd.read_csv("/content/drive/MyDrive/nltm/label_inference/final_file.csv")

In [32]:
df.head()

,Unnamed: 0,DOC_NO,SENT_NO,ID,FORM,LEMMA,CATEGORY,POS,FEAT,HEAD,DEPREL,DEPS,MISC,sentence,HEAD_PRED,DEPREL_PRED
0,0,/content/drive/MyDrive/nltm/test_,1,1,इसके,यह,pn,PRP,cat-pn|gen-any|num-sg|pers-3|case-o|vib-0_अतिर...,13,vmod,_,_,"इसके अतिरिक्त गुग्गुल कुंड , भीम गुफा तथा भीमश...",13,vmod
1,1,/content/drive/MyDrive/nltm/test_,1,2,अतिरिक्त,अतिरिक्त,psp,PSP,cat-psp|gen-|num-|pers-|case-|vib-|tam-|chunkI...,1,lwg__psp,_,_,"इसके अतिरिक्त गुग्गुल कुंड , भीम गुफा तथा भीमश...",1,lwg__psp
2,2,/content/drive/MyDrive/nltm/test_,1,3,गुग्गुल,गुग्गुल,n,NNPC,cat-n|gen-m|num-sg|pers-3|case-d|vib-0|tam-0|c...,4,pof__cn,_,_,"इसके अतिरिक्त गुग्गुल कुंड , भीम गुफा तथा भीमश...",4,pof__cn
3,3,/content/drive/MyDrive/nltm/test_,1,4,कुंड,कुंड,n,NNP,cat-n|gen-m|num-sg|pers-3|case-d|vib-0|tam-0|c...,8,ccof,_,_,"इसके अतिरिक्त गुग्गुल कुंड , भीम गुफा तथा भीमश...",8,ccof
4,4,/content/drive/MyDrive/nltm/test_,1,5,",",COMMA,punc,SYM,cat-punc|gen-|num-|pers-|case-|vib-|tam-|chunk...,4,rsym,_,_,"इसके अतिरिक्त गुग्गुल कुंड , भीम गुफा तथा भीमश...",4,rsym

In [79]:
meanings.head()

  Label                      Meaning(Sanskrit)          Meaning(English)
0    k1                                 kartaa        doer/agent/subject
1   pk1                        prayojaka karta                    causer
2   jk1                         prayojya karta                    causee
3   mk1                       madhyastha karta           mediator causer
4   k1s  vidheya karta - karta samanadhikarana  noun complement of karta

#Support

In [58]:
def support(label1,label2):
  idx_l1=int(conf_mat[conf_mat['Labels']==label1].index.values)
  idx_l2=int(conf_mat[conf_mat['Labels']==label2].index.values)
  columns=['label','Train_support','Test_support']
  support=pd.DataFrame(columns=columns)
  support.loc[len(support.index)] = [label1, conf_mat['Training_support'][idx_l1], conf_mat['Test Support'][idx_l1]]
  support.loc[len(support.index)] = [label2, conf_mat['Training_support'][idx_l2], conf_mat['Test Support'][idx_l2]]
  print(support)

#Confusion Pair

In [125]:
def info(idx,label1,label2):
  columns=['label_type','labels','Meaning_Sanskrit','Meaning_English']
  conf=pd.DataFrame(columns=columns)
  conf['label_type']=['annotated label', 'predicted label']
  conf['labels']=[label1,label2]
  def meaningS(i):
    return meanings.loc[meanings['Label'] == conf['labels'][i], 'Meaning(Sanskrit)'].iloc[0]
  def meaningE(i):
    return meanings.loc[meanings['Label'] == conf['labels'][i], 'Meaning(English)'].iloc[0]
  if label1 in meanings['Label'].values:
    if label2 in meanings['Label'].values:
      conf['Meaning_Sanskrit']= [meaningS(0),meaningS(1)]
      conf['Meaning_English']=[meaningE(0),meaningE(1)]
    else:
      conf['Meaning_English'][0]=meaningE(0)
      conf['Meaning_Sanskrit'][0]=meaningS(0)
  elif label2 in meanings['Label'].values:
    conf['Meaning_English'][1]=meaningE(1)
    conf['Meaning_Sanskrit'][1]=meaningS(1)
  print(conf)
  print("\n")
  print(df['sentence'][idx] + "\nword: "+ df['FORM'][idx] + "\tsent_id: " + str(df['ID'][idx]) + "\n")
  print(support(label1,label2))
  input("Press Enter for next example: ")

In [ ]:
label1="nmod__k2inv"
label2="nmod"

for idx in range(len(df)):
  if df['DEPREL'][idx]==label1 and df['DEPREL_PRED'][idx]==label2:
    info(idx,label1,label2)
if idx>=(len(df)-1):
  print("No more confustion pairs..")